version: '3.7'
services:
  bot:
    image: marusoftware/discord-integrator:latest
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    init: true
    restart: always
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST:-db}:${POSTGRES_PORT:-5432}/${POSTGRES_DB}
  db:
    image: marusoftware/postgres:15-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always
    env_file:
      - .env
    healthcheck:
      test: "pg_isready -U $$POSTGRES_USER"
      interval: 2s
      timeout: 5s
      retries: 5

volumes:
  postgres:
